name: giving server names by developers

on:
  workflow_dispatch:
    inputs:
      servername:
        description: 'adding the name of the server in the server group'
        required: true
        default: "hi"

      

# env:
#   servername: ${{ github.event.inputs.servername }}

jobs:
  servernamejob:
    runs-on: ubuntu-latest
#     env:
#       Greeting: Hello
    steps:
      - name: "Say servername"
        run: echo "server is ${{ github.event.inputs.servername }}"

